### ISSUE TITLE
Running entire application in the backend

### ISSUE THREAD

**Issue by isabirahmed** [markusmobius/nodeSavePageWE#1]
Hey Mark,
Thank you for putting this solution together.
I was wondering instead of using the client part of the code which needs to be run in the chrome context, can we move it entirely into puppeteer?

Or is there an alternative solution that does this?
Thanks!

**Comment by markusmobius** [comment]
I am not sure that's efficient. Essentially, you would need to query the page a lot from puppeteer which goes through devtools protocol which I found very slow. I found it usually much faster to instead inject scripts into the page and then pipe back output (so you only interact once with the page - injecting the script and getting back output).
