### ISSUE TITLE
The CSS file won't add to single HTML file. 

### ISSUE THREAD

**Issue by ibrahimrajabli** [markusmobius/nodeSavePageWE#5]
The CSS file can not add to single HTML file. 
you can try with this URL "https://bakujobs.az/vacancy/production-company-recruitment-talent-aquisition-lead/250"
but I added function of taking screenshots to the nodeSavePageWE.js file then screenshot is pretty normal. but HTML code is without CSS.

**Comment by markusmobius** [comment]
I just updated the code to base it on the 2023 version of savepageWE. Your example now seems to work fine.
